#!/bin/bash
inPath=/YOUR-LOCAL-DIRECTORY/SteinForestProblem/SteinForestLibrary/  # replace the directory of Instances
outPath=/YOUR-LOCAL-DIRECTORY/SteinForestProblem/Results/ # replace the Results directory

############################################################
# Reading: SF-Instances-NM
file1=Sparse-Graphs/B/

./SFout $inPath $outPath $file1 b01.stp PD 1
./SFout $inPath $outPath $file1 b02.stp PD 1
./SFout $inPath $outPath $file1 b03.stp PD 1
./SFout $inPath $outPath $file1 b04.stp PD 1
./SFout $inPath $outPath $file1 b05.stp PD 1
./SFout $inPath $outPath $file1 b06.stp PD 1
./SFout $inPath $outPath $file1 b07.stp PD 1
./SFout $inPath $outPath $file1 b08.stp PD 1
./SFout $inPath $outPath $file1 b09.stp PD 1
./SFout $inPath $outPath $file1 b10.stp PD 1
./SFout $inPath $outPath $file1 b11.stp PD 1
./SFout $inPath $outPath $file1 b12.stp PD 1
./SFout $inPath $outPath $file1 b13.stp PD 1
./SFout $inPath $outPath $file1 b14.stp PD 1
./SFout $inPath $outPath $file1 b15.stp PD 1
./SFout $inPath $outPath $file1 b16.stp PD 1
./SFout $inPath $outPath $file1 b17.stp PD 1
./SFout $inPath $outPath $file1 b18.stp PD 1

./SFout $inPath $outPath $file1 b01.stp PG 1
./SFout $inPath $outPath $file1 b02.stp PG 1
./SFout $inPath $outPath $file1 b03.stp PG 1
./SFout $inPath $outPath $file1 b04.stp PG 1
./SFout $inPath $outPath $file1 b05.stp PG 1
./SFout $inPath $outPath $file1 b06.stp PG 1
./SFout $inPath $outPath $file1 b07.stp PG 1
./SFout $inPath $outPath $file1 b08.stp PG 1
./SFout $inPath $outPath $file1 b09.stp PG 1
./SFout $inPath $outPath $file1 b10.stp PG 1
./SFout $inPath $outPath $file1 b11.stp PG 1
./SFout $inPath $outPath $file1 b12.stp PG 1
./SFout $inPath $outPath $file1 b13.stp PG 1
./SFout $inPath $outPath $file1 b14.stp PG 1
./SFout $inPath $outPath $file1 b15.stp PG 1
./SFout $inPath $outPath $file1 b16.stp PG 1
./SFout $inPath $outPath $file1 b17.stp PG 1
./SFout $inPath $outPath $file1 b18.stp PG 1

./SFout $inPath $outPath $file1 b01.stp GL 1
./SFout $inPath $outPath $file1 b02.stp GL 1
./SFout $inPath $outPath $file1 b03.stp GL 1
./SFout $inPath $outPath $file1 b04.stp GL 1
./SFout $inPath $outPath $file1 b05.stp GL 1
./SFout $inPath $outPath $file1 b06.stp GL 1
./SFout $inPath $outPath $file1 b07.stp GL 1
./SFout $inPath $outPath $file1 b08.stp GL 1
./SFout $inPath $outPath $file1 b09.stp GL 1
./SFout $inPath $outPath $file1 b10.stp GL 1
./SFout $inPath $outPath $file1 b11.stp GL 1
./SFout $inPath $outPath $file1 b12.stp GL 1
./SFout $inPath $outPath $file1 b13.stp GL 1
./SFout $inPath $outPath $file1 b14.stp GL 1
./SFout $inPath $outPath $file1 b15.stp GL 1
./SFout $inPath $outPath $file1 b16.stp GL 1
./SFout $inPath $outPath $file1 b17.stp GL 1
./SFout $inPath $outPath $file1 b18.stp GL 1

./SFout $inPath $outPath $file1 b01.stp TM 1
./SFout $inPath $outPath $file1 b02.stp TM 1
./SFout $inPath $outPath $file1 b03.stp TM 1
./SFout $inPath $outPath $file1 b04.stp TM 1
./SFout $inPath $outPath $file1 b05.stp TM 1
./SFout $inPath $outPath $file1 b06.stp TM 1
./SFout $inPath $outPath $file1 b07.stp TM 1
./SFout $inPath $outPath $file1 b08.stp TM 1
./SFout $inPath $outPath $file1 b09.stp TM 1
./SFout $inPath $outPath $file1 b10.stp TM 1
./SFout $inPath $outPath $file1 b11.stp TM 1
./SFout $inPath $outPath $file1 b12.stp TM 1
./SFout $inPath $outPath $file1 b13.stp TM 1
./SFout $inPath $outPath $file1 b14.stp TM 1
./SFout $inPath $outPath $file1 b15.stp TM 1
./SFout $inPath $outPath $file1 b16.stp TM 1
./SFout $inPath $outPath $file1 b17.stp TM 1
./SFout $inPath $outPath $file1 b18.stp TM 1
